//! Generate the Dagger Rust SDK's API bindings from an introspection schema.
//!
//! Usage:
//!
//! ```text
//! codegen --introspection <schema.json> --outdir <dir>
//! ```
//!
//! Reads the engine's GraphQL introspection schema and writes a Rust module
//! tree to `--outdir`, which `dagger generate` vendors into each module at
//! `dagger_sdk/src/gen/`.
//!
//! Like everything else in this repository, this is `no_std` and built on
//! goish. It reaches for `os` where a hosted binary would reach for `std::fs`,
//! and its one dependency is the same goish rev the SDK crate and every
//! generated module pin. Nothing here comes from crates.io, so `dagger
//! generate` needs no registry access beyond the toolchain image.
//!
//! # Status
//!
//! Scaffold: the schema is read and validated, but the emitted bindings are a
//! placeholder. Generating the real surface — one type per GraphQL object, with
//! a lazily-built selection per method, mirroring the Go SDK's `dagger.gen.go`
//! — is the next milestone. goish's `encoding/json` is what will parse the
//! schema when that lands; no serde equivalent is needed.

#![no_std]
#![no_main]

use goish::{bytes, fmt, len, nil, os, string};

/// Write a message to stderr and exit non-zero.
fn fail(msg: string) -> ! {
    let stderr = os::Stderr();
    let _ = stderr.Write(bytes(string("codegen: ") + msg + "\n"));
    os::Exit(1)
}

/// Parse `--introspection` and `--outdir` out of argv.
///
/// Both are required; anything else is an error rather than a silent default,
/// so a typo in mod.dang surfaces here instead of producing empty bindings.
fn parse_args() -> (string, string) {
    let args = os::Args();
    let argc = len(&args);

    let mut introspection = string("");
    let mut outdir = string("");

    // argv[0] is the program name.
    let mut i: goish::int = 1;
    while i < argc {
        let flag = args[i as usize].clone();
        if i + 1 >= argc {
            fail(flag + " requires a value");
        }
        let value = args[(i + 1) as usize].clone();

        if flag == "--introspection" {
            introspection = value;
        } else if flag == "--outdir" {
            outdir = value;
        } else {
            fail(string("unknown argument: ") + flag);
        }
        i += 2;
    }

    if introspection.Len() == 0 {
        fail(string("missing --introspection"));
    }
    if outdir.Len() == 0 {
        fail(string("missing --outdir"));
    }

    (introspection, outdir)
}

/// Render the bindings module.
///
/// The schema is measured rather than parsed: recording its size keeps the
/// output a function of the input, so a schema change shows up as a diff in the
/// generated file instead of silently producing identical output.
fn bindings(schema_len: goish::int) -> string {
    fmt::Sprintf!(
        "//! API bindings generated from this module's introspection schema.\n\
         //!\n\
         //! Generated by `sdk/codegen` — do not edit. Re-run `dagger generate`.\n\
         //!\n\
         //! This is a scaffold: the real binding surface is not generated yet.\n\
         //! Calling into it will not reach the engine.\n\
         \n\
         /// Byte length of the introspection schema these bindings were generated from.\n\
         pub const SCHEMA_LEN: usize = %d;\n",
        schema_len
    )
}

#[goish::main]
fn main() {
    let (introspection, outdir) = parse_args();

    let (schema, err) = os::ReadFile(introspection.clone());
    if err != nil {
        fail(string("read ") + introspection + ": " + fmt::Sprintf!("%v", err));
    }

    let schema_len = len(&schema);
    if schema_len == 0 {
        fail(introspection + " is empty");
    }

    let err = os::MkdirAll(outdir.clone(), 0o755);
    if err != nil {
        fail(string("create ") + outdir + ": " + fmt::Sprintf!("%v", err));
    }

    let out = outdir + "/mod.rs";
    let err = os::WriteFile(out.clone(), bytes(bindings(schema_len)), 0o644);
    if err != nil {
        fail(string("write ") + out + ": " + fmt::Sprintf!("%v", err));
    }
}
