//! Generate the Dagger Rust SDK's API bindings from an introspection schema.
//!
//! Usage:
//!
//! ```text
//! codegen --introspection <schema.json> --outdir <dir>
//! ```
//!
//! Reads the engine's GraphQL introspection schema and writes a Rust module
//! tree to `--outdir`, which `dagger generate` vendors into each module at
//! `dagger_sdk/src/gen/`.
//!
//! # Status
//!
//! Scaffold: the schema is read and validated, but the emitted bindings are a
//! placeholder. Generating the real surface — one type per GraphQL object, with
//! a lazily-built selection per method, mirroring the Go SDK's `dagger.gen.go`
//! — is the next milestone.

use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

fn main() -> ExitCode {
    match run(std::env::args().skip(1).collect()) {
        Ok(()) => ExitCode::SUCCESS,
        Err(err) => {
            let _ = writeln!(io::stderr(), "codegen: {err}");
            ExitCode::FAILURE
        }
    }
}

struct Args {
    introspection: PathBuf,
    outdir: PathBuf,
}

fn run(args: Vec<String>) -> Result<(), String> {
    let args = parse_args(args)?;

    let schema = fs::read_to_string(&args.introspection)
        .map_err(|e| format!("read {}: {e}", args.introspection.display()))?;
    if schema.trim().is_empty() {
        return Err(format!("{} is empty", args.introspection.display()));
    }

    fs::create_dir_all(&args.outdir)
        .map_err(|e| format!("create {}: {e}", args.outdir.display()))?;

    write_file(
        &args.outdir.join("mod.rs"),
        &bindings(&schema),
    )
}

fn parse_args(args: Vec<String>) -> Result<Args, String> {
    let mut introspection = None;
    let mut outdir = None;

    let mut rest = args.into_iter();
    while let Some(flag) = rest.next() {
        let target = match flag.as_str() {
            "--introspection" => &mut introspection,
            "--outdir" => &mut outdir,
            other => return Err(format!("unknown argument: {other}")),
        };
        let value = rest
            .next()
            .ok_or_else(|| format!("{flag} requires a value"))?;
        *target = Some(PathBuf::from(value));
    }

    Ok(Args {
        introspection: introspection.ok_or("missing --introspection")?,
        outdir: outdir.ok_or("missing --outdir")?,
    })
}

/// Render the bindings module.
///
/// The schema is measured rather than parsed: recording its size keeps the
/// output a function of the input, so a schema change shows up as a diff in the
/// generated file instead of silently producing identical output.
fn bindings(schema: &str) -> String {
    format!(
        "//! API bindings generated from this module's introspection schema.\n\
         //!\n\
         //! Generated by `sdk/codegen` — do not edit. Re-run `dagger generate`.\n\
         //!\n\
         //! This is a scaffold: the real binding surface is not generated yet.\n\
         //! Calling into it will not reach the engine.\n\
         \n\
         /// Byte length of the introspection schema these bindings were generated from.\n\
         pub const SCHEMA_LEN: usize = {};\n",
        schema.len(),
    )
}

fn write_file(path: &Path, contents: &str) -> Result<(), String> {
    fs::write(path, contents).map_err(|e| format!("write {}: {e}", path.display()))
}
