//! Emitting the bindings.
//!
//! One file, `mod.rs`, holding the whole API surface, written against the
//! hand-rolled half of the SDK — [`querybuilder`] for building and decoding a
//! selection, [`engine`] for sending one. Nothing here invents a runtime; the
//! generated code is a thin, typed face over those two.
//!
//! [`querybuilder`]: https://docs.rs/dagger
//! [`engine`]: https://docs.rs/dagger
//!
//! # What each schema kind becomes
//!
//! | schema | Rust |
//! | --- | --- |
//! | `OBJECT`, `INTERFACE` | `struct X { transport, q }` plus a zero-sized `XFields` |
//! | `ENUM` | a fieldless `enum`, with `FromJson` and `ToArg` |
//! | `INPUT_OBJECT` | a plain `struct`, with `ToArg` |
//! | `SCALAR` | nothing — see below |
//!
//! Scalars are the one kind with no generated type. All of them but `Void` are
//! string-backed — `ID`, `Platform`, `JSON`, and the whole `ContainerID` family
//! — and the schema hands them back as plain `ID`, never as the narrower name:
//! `Container.id` is declared `ID!`, while `loadContainerFromID` takes a
//! `ContainerID!`. A newtype per scalar would therefore be a type no method
//! ever returns and every caller has to construct, so they all map to `string`
//! and the loaders document what kind of ID they want. `Void` is the exception,
//! and is emitted as a unit struct that decodes from the null it comes back as.
//!
//! # Two methods per field, not one
//!
//! An argument is optional exactly when it is nullable — no non-null argument
//! in the schema carries a default — and Rust has no optional parameters. So a
//! field with nullable arguments gets a pair: `file(path)` and
//! `file_opts(path, opts)`, where the opts are a generated struct that derives
//! `Default`. The pair is emitted on the object and on its `Fields` namespace
//! alike, sharing one opts struct between them.
//!
//! # Objects come back as IDs
//!
//! An object-typed *field* extends the chain, which costs nothing and cannot
//! fail. A *list* of objects cannot: there is no chain that points at element
//! three, so the list is fetched as IDs and each element rebuilt through the
//! matching `loadXFromID`. An element type with no loader is the one shape that
//! is skipped — the field stays reachable through `fetch`, which needs no ID.
//!
//! The same round trip is what a module function's arguments are made of, so
//! every object with a loader also gets an `impl crate::ObjectId` — see
//! [`Renderer::object_id`]. That is the whole of what lets a module take a
//! `Directory` and hand back a `Container`.

use goish::{append, fmt, int, make, slice, string, strings};

use crate::names::{enum_variant, escape_ident, rust_name, snake_case, upper_first};
use crate::schema::{Field, InputValue, Schema, Type, TypeRef};

/// Methods the generated `impl` blocks already define, which a schema field of
/// the same name would collide with.
const RESERVED_METHODS: &[&str] = &["new", "fetch"];

/// Render the whole bindings module.
pub fn render(schema: &Schema) -> string {
    let mut r = Renderer {
        schema,
        out: strings::Builder::new(),
    };
    r.run();
    r.out.String()
}

struct Renderer<'a> {
    schema: &'a Schema,
    out: strings::Builder,
}

impl<'a> Renderer<'a> {
    fn w(&mut self, text: impl Into<string>) {
        let _ = self.out.WriteString(text);
    }

    fn run(&mut self) {
        self.header();

        let mut i: int = 0;
        while i < self.schema.types.Len() {
            let ty = self.schema.types[i].clone();
            i += 1;

            if is_meta(&ty.name) || ty.name.Len() == 0 {
                continue;
            }
            if ty.kind == "ENUM" {
                self.enum_type(&ty);
            } else if ty.kind == "INPUT_OBJECT" {
                self.input_object(&ty);
            } else if ty.kind == "OBJECT" || ty.kind == "INTERFACE" {
                self.object(&ty);
            }
        }

        self.root();
    }

    // ─── preamble ─────────────────────────────────────────────────────

    fn header(&mut self) {
        self.w(concat!(
            "//! API bindings generated from this module's introspection schema.\n",
            "//!\n",
            "//! Generated by `sdk/codegen` — do not edit. Re-run `dagger generate`.\n",
            "//!\n",
            "//! Every object holds the transport it was reached through, so a value taken\n",
            "//! out of one call can be used in the next without being handed a session\n",
            "//! again. [`dag`] is where the first one comes from, and\n",
            "//! [`ObjectId`](crate::ObjectId) — implemented by every object with a loader —\n",
            "//! is where one handed to a module function comes from.\n",
            "//!\n",
            "//! Reading a field sends a query. Reading several sends one query:\n",
            "//!\n",
            "//! ```ignore\n",
            "//! let ctr = dag().container().from(\"alpine\").with_exec(&[\"echo\", \"hi\"]);\n",
            "//! let (out, platform) = ctr.fetch(|c| (c.stdout(), c.platform()))?;\n",
            "//! ```\n",
            "\n",
            "// Schema names are kept as they are written in the schema. That keeps the\n",
            "// generated surface searchable against the API docs, and it is the only\n",
            "// spelling that stays injective: `ImageLayerCompression` holds both `Gzip` and\n",
            "// `GZIP`, and folding case would collapse them into one variant.\n",
            "#![allow(non_camel_case_types)]\n",
            "#![allow(non_snake_case)]\n",
            "// A generated wrapper calls its own `_opts` twin, so a deprecated field would\n",
            "// warn about itself. A caller outside this module still sees the warning.\n",
            "#![allow(deprecated)]\n",
            "// Not every schema uses every helper — a small one may name no enum at all.\n",
            "#![allow(unused_imports)]\n",
            "\n",
            "use alloc::sync::Arc;\n",
            "\n",
            "use goish::encoding::json;\n",
            "use goish::{append, float64, int, make, slice, string};\n",
            "\n",
            "use crate::engine::{self, Transport};\n",
            "use crate::querybuilder::{\n",
            "    arg_list, arg_string, Args, Chain, Field, Fields, FromJson, Leaf, ListField, OptField,\n",
            "    Sel, ToArg,\n",
            "};\n",
            "\n",
            "/// The `Void` scalar: a field that returns nothing.\n",
            "///\n",
            "/// It arrives as JSON null, so decoding accepts whatever it is handed — the\n",
            "/// value carries no information, only the fact that the call completed.\n",
            "#[derive(Clone, Copy, Default, PartialEq, Eq)]\n",
            "pub struct Void;\n",
            "\n",
            "impl FromJson for Void {\n",
            "    fn from_json(_value: &json::Value) -> Result<Void, string> {\n",
            "        Ok(Void)\n",
            "    }\n",
            "}\n",
        ));
    }

    /// The free functions that open an API root: one over the process's own
    /// session, one over a transport the caller supplies.
    fn root(&mut self) {
        let query = self.schema.query_type.clone();
        if self.schema.find(&query).is_none() {
            return;
        }

        self.w("\n/// The API root, over the session this process was started in.\n");
        self.w("///\n");
        self.w("/// Every other object is reached from here, and inherits its transport.\n");
        self.w("/// The session comes from the environment the engine set, so this is the\n");
        self.w("/// spelling a module wants; see `dag_with` to supply a transport instead.\n");
        self.w(fmt::Sprintf!(
            "pub fn dag() -> %s {\n    dag_with(engine::default_transport())\n}\n",
            query
        ));

        self.w("\n/// The API root, reached over `transport`.\n");
        self.w("///\n");
        self.w("/// What [`dag`] is built on, for a caller with its own transport — a test\n");
        self.w("/// double, a recording proxy, a session it opened itself.\n");
        self.w(fmt::Sprintf!(
            "pub fn dag_with(transport: Arc<dyn Transport>) -> %s {\n    %s::new(transport, Chain::root())\n}\n",
            query,
            query
        ));
    }

    // ─── enums ────────────────────────────────────────────────────────

    fn enum_type(&mut self, ty: &Type) {
        let mut values = make!([]string, 0, ty.enum_values.Len());
        let mut i: int = 0;
        while i < ty.enum_values.Len() {
            values = append!(values, ty.enum_values[i].name.clone());
            i += 1;
        }

        self.w("\n");
        self.doc("", &ty.doc);
        self.w("#[derive(Clone, Copy, PartialEq, Eq)]\n");
        self.w(fmt::Sprintf!("pub enum %s {\n", ty.name));
        let mut i: int = 0;
        while i < ty.enum_values.Len() {
            let value = ty.enum_values[i].clone();
            self.doc("    ", &value.doc);
            self.w(fmt::Sprintf!("    %s,\n", enum_variant(&value.name, &values)));
            i += 1;
        }
        self.w("}\n\n");

        self.w(fmt::Sprintf!("impl %s {\n", ty.name));
        self.w("    /// The value as the schema spells it, which is what a query carries.\n");
        self.w("    pub fn as_str(&self) -> &'static str {\n");
        self.w("        match self {\n");
        let mut i: int = 0;
        while i < ty.enum_values.Len() {
            let value = ty.enum_values[i].name.clone();
            self.w(fmt::Sprintf!(
                "            %s::%s => %q,\n",
                ty.name,
                enum_variant(&value, &values),
                value
            ));
            i += 1;
        }
        self.w("        }\n    }\n}\n\n");

        // A GraphQL enum literal is a bare name, so it is spliced unquoted.
        self.w(fmt::Sprintf!(
            concat!(
                "impl ToArg for %s {\n",
                "    fn to_arg(&self) -> string {\n",
                "        string(self.as_str())\n",
                "    }\n",
                "}\n",
                "\n",
            ),
            ty.name
        ));

        self.w(fmt::Sprintf!(
            concat!(
                "impl FromJson for %s {\n",
                "    fn from_json(value: &json::Value) -> Result<%s, string> {\n",
                "        let found = match value.AsString() {\n",
                "            Some(found) => found,\n",
                "            None => return Err(string(\"expected a string\")),\n",
                "        };\n",
            ),
            ty.name,
            ty.name
        ));
        let mut i: int = 0;
        while i < ty.enum_values.Len() {
            let value = ty.enum_values[i].name.clone();
            self.w(fmt::Sprintf!(
                concat!(
                    "        if found == %q {\n",
                    "            return Ok(%s::%s);\n",
                    "        }\n",
                ),
                value,
                ty.name,
                enum_variant(&value, &values)
            ));
            i += 1;
        }
        self.w(fmt::Sprintf!(
            concat!(
                "        Err(string(\"not a %s: \") + found.clone())\n",
                "    }\n",
                "}\n",
            ),
            ty.name
        ));
    }

    // ─── input objects ────────────────────────────────────────────────

    fn input_object(&mut self, ty: &Type) {
        self.w("\n");
        self.doc("", &ty.doc);
        self.w("#[derive(Clone)]\n");
        self.w(fmt::Sprintf!("pub struct %s {\n", ty.name));
        let mut i: int = 0;
        while i < ty.input_fields.Len() {
            let field = ty.input_fields[i].clone();
            self.doc("    ", &field.doc);
            self.w(fmt::Sprintf!(
                "    pub %s: %s,\n",
                rust_name(&field.name),
                owned_field_type(&field.ty)
            ));
            i += 1;
        }
        self.w("}\n\n");

        self.w(fmt::Sprintf!(
            concat!(
                "impl ToArg for %s {\n",
                "    fn to_arg(&self) -> string {\n",
                "        let mut __args = Args::new();\n",
            ),
            ty.name
        ));
        let mut i: int = 0;
        while i < ty.input_fields.Len() {
            let field = ty.input_fields[i].clone();
            let access = string("self.") + rust_name(&field.name);
            if field.ty.non_null {
                // An input object owns its fields, so a required one is
                // borrowed rather than moved out of `&self`. The optional case
                // below already borrows, through the `if let`.
                let borrowed = if borrows_to_encode(&field.ty) {
                    string("&") + access.clone()
                } else {
                    access.clone()
                };
                self.w(fmt::Sprintf!(
                    "        __args.put(%q, %s);\n",
                    field.name,
                    encode(&borrowed, &field.ty)
                ));
            } else {
                self.w(fmt::Sprintf!(
                    concat!(
                        "        if let Some(value) = &%s {\n",
                        "            __args.put(%q, %s);\n",
                        "        }\n",
                    ),
                    access,
                    field.name,
                    encode(&string("value"), &field.ty)
                ));
            }
            i += 1;
        }
        self.w("        __args.object()\n");
        self.w("    }\n}\n");
    }

    // ─── objects ──────────────────────────────────────────────────────

    fn object(&mut self, ty: &Type) {
        let fields_type = ty.name.clone() + "Fields";

        // Opts structs first: both impl blocks below name them.
        let mut i: int = 0;
        while i < ty.fields.Len() {
            let field = ty.fields[i].clone();
            i += 1;
            if self.skip(&field) {
                continue;
            }
            if optional_args(&field).Len() > 0 {
                self.opts_struct(ty, &field);
            }
        }

        self.w("\n");
        self.doc("", &ty.doc);
        self.w(fmt::Sprintf!(
            "pub struct %s {\n    transport: Arc<dyn Transport>,\n    q: Chain,\n}\n\n",
            ty.name
        ));

        self.w(fmt::Sprintf!("impl %s {\n", ty.name));
        self.w(fmt::Sprintf!(
            concat!(
                "    /// Build one from a transport and the chain that reaches it.\n",
                "    pub fn new(transport: Arc<dyn Transport>, q: Chain) -> %s {\n",
                "        %s { transport, q }\n",
                "    }\n",
                "\n",
            ),
            ty.name,
            ty.name
        ));
        self.w(fmt::Sprintf!(
            concat!(
                "    /// Read several fields of this object in one round trip.\n",
                "    ///\n",
                "    /// The closure is handed a namespace of every field this object has, and\n",
                "    /// returns a tuple of what to read.\n",
                "    pub fn fetch<S: Sel>(\n",
                "        &self,\n",
                "        select: impl FnOnce(&%s) -> S,\n",
                "    ) -> Result<S::Out, string> {\n",
                "        engine::fetch(&*self.transport, &self.q, &select(&%s::new()))\n",
                "    }\n",
            ),
            fields_type,
            fields_type
        ));

        let mut i: int = 0;
        while i < ty.fields.Len() {
            let field = ty.fields[i].clone();
            i += 1;
            if self.skip(&field) {
                continue;
            }
            self.object_field(ty, &field);
        }
        self.w("}\n\n");

        self.object_id(ty);

        self.doc(
            "",
            &fmt::Sprintf!(
                concat!(
                    "The fields of [`%s`], for [`%s::fetch`].\n",
                    "\n",
                    "A zero-sized namespace: it carries no data, only the field set.",
                ),
                ty.name,
                ty.name
            ),
        );
        self.w(fmt::Sprintf!(
            concat!(
                "pub struct %s;\n",
                "\n",
                "impl Fields for %s {\n",
                "    fn new() -> %s {\n",
                "        %s\n",
                "    }\n",
                "}\n",
                "\n",
                "impl %s {\n",
            ),
            fields_type,
            fields_type,
            fields_type,
            fields_type,
            fields_type
        ));
        let mut first = true;
        let mut i: int = 0;
        while i < ty.fields.Len() {
            let field = ty.fields[i].clone();
            i += 1;
            if self.skip(&field) {
                continue;
            }
            if !first {
                self.w("\n");
            }
            first = false;
            self.selection_field(ty, &field);
        }
        self.w("}\n");
    }

    /// The `ObjectId` impl that lets this type cross a module function's
    /// boundary.
    ///
    /// An object is passed to a module function, and returned from one, as its
    /// id, so the two directions are the two halves of the trait: `from_id`
    /// starts a fresh chain at the type's loader, and `to_id` runs the chain it
    /// is called on and reads the id off the end.
    ///
    /// It takes both a loader and an `id` field to do that, and a type missing
    /// either simply does not implement the trait — using one in a signature is
    /// then a compile error in the module, which is where it belongs. Almost
    /// everything in the engine's schema has both: of the 70 objects in v0.21,
    /// the four without are `Query`, the `Node` interface, and the two
    /// `_DirectiveApplication` types.
    fn object_id(&mut self, ty: &Type) {
        let loader = self.loader(&ty.name);
        let id_type = self.id_type(&ty.name);
        let loader = match (loader, id_type) {
            // Every id in this schema is an `ID`-family scalar, which is text.
            // Anything else could not be handed back to a loader that takes
            // one, so it counts as no id at all.
            (Some(loader), Some(id_type)) if id_type == "string" => loader,
            _ => {
                // A plain comment, not a doc comment: `impl` blocks are what
                // surround it, and a `///` here would document whichever item
                // came next.
                self.w(fmt::Sprintf!(
                    concat!(
                        "// `%s` has no loader taking an id, so it cannot be rebuilt from one: it is not an\n",
                        "// `ObjectId`, and a module function cannot take or return it.\n",
                        "\n",
                    ),
                    ty.name
                ));
                return;
            }
        };

        self.w(fmt::Sprintf!(
            concat!(
                "impl crate::ObjectId for %s {\n",
                "    fn from_id(id: string) -> %s {\n",
                "        let mut __id = Args::new();\n",
                "        __id.put(\"id\", arg_string(id));\n",
                "        %s::new(\n",
                "            engine::default_transport(),\n",
                "            Chain::root().field(%q, __id.finish()),\n",
                "        )\n",
                "    }\n",
                "\n",
                "    fn to_id(&self) -> Result<string, string> {\n",
                "        engine::fetch(&*self.transport, &self.q, &Leaf::<string>::new(\"id\"))\n",
                "    }\n",
                "}\n",
                "\n",
            ),
            ty.name,
            ty.name,
            ty.name,
            loader
        ));
    }

    /// Whether a field cannot be rendered at all.
    ///
    /// Only a malformed type reference qualifies: everything the engine
    /// declares has a name, so this is a guard rather than a policy.
    fn skip(&self, field: &Field) -> bool {
        field.name.Len() == 0 || field.ty.name.Len() == 0
    }

    fn opts_struct(&mut self, ty: &Type, field: &Field) {
        let optional = optional_args(field);
        let name = opts_name(ty, field);
        let lifetime = if opts_borrows(&optional) { "<'a>" } else { "" };

        self.w("\n");
        self.doc(
            "",
            &fmt::Sprintf!(
                concat!(
                    "The optional arguments of [`%s::%s`].\n",
                    "\n",
                    "Every field left `None` is left out of the query, so the engine applies its own default.",
                ),
                ty.name,
                method_name(field)
            ),
        );
        self.w("#[derive(Clone, Default)]\n");
        self.w(fmt::Sprintf!("pub struct %s%s {\n", name, lifetime));
        let mut i: int = 0;
        while i < optional.Len() {
            let arg = optional[i].clone();
            self.doc("    ", &arg_doc(&arg));
            self.w(fmt::Sprintf!(
                "    pub %s: %s,\n",
                rust_name(&arg.name),
                opts_field_type(&arg.ty)
            ));
            i += 1;
        }
        self.w("}\n");
    }

    /// The `let mut __args = …` block shared by every rendering of one field.
    ///
    /// A field with no arguments gets no block at all: an `__args` nobody reads
    /// would only be a warning in every generated module.
    fn args_block(&mut self, field: &Field, with_opts: bool) {
        if field.args.Len() == 0 {
            return;
        }
        self.w("        let mut __args = Args::new();\n");

        let mut i: int = 0;
        while i < field.args.Len() {
            let arg = field.args[i].clone();
            i += 1;
            if !arg.ty.non_null {
                continue;
            }
            self.w(fmt::Sprintf!(
                "        __args.put(%q, %s);\n",
                arg.name,
                encode(&rust_name(&arg.name), &arg.ty)
            ));
        }

        if !with_opts {
            return;
        }

        let optional = optional_args(field);
        let mut i: int = 0;
        while i < optional.Len() {
            let arg = optional[i].clone();
            i += 1;
            self.w(fmt::Sprintf!(
                "        if let Some(value) = opts.%s {\n",
                rust_name(&arg.name)
            ));
            self.w(fmt::Sprintf!(
                "            __args.put(%q, %s);\n",
                arg.name,
                encode(&string("value"), &arg.ty)
            ));
            self.w("        }\n");
        }
    }

    /// The two signatures a field is reachable through, and the bodies behind
    /// them.
    ///
    /// `body` writes the method body, which is always one level in — a method
    /// body has only ever one depth here, so the indent is a literal in what
    /// `body` writes rather than a parameter threaded through it.
    fn field_pair(
        &mut self,
        ty: &Type,
        field: &Field,
        return_type: string,
        body: &dyn Fn(&mut Renderer<'a>),
    ) {
        let optional = optional_args(field);
        let required = required_args(field);
        let params = param_list(&required);
        let name = method_name(field);

        if optional.Len() == 0 {
            self.w("\n");
            self.doc("    ", &field_doc(field));
            self.deprecation("    ", field);
            self.w(fmt::Sprintf!(
                "    pub fn %s(&self%s) -> %s {\n",
                name,
                params,
                return_type
            ));
            self.args_block(field, false);
            body(self);
            self.w("    }\n");
            return;
        }

        let opts_type = opts_name(ty, field);
        let opts_param = if opts_borrows(&optional) {
            opts_type.clone() + "<'_>"
        } else {
            opts_type.clone()
        };
        let with_opts = opts_method_name(field);

        self.w("\n");
        self.doc("    ", &field_doc(field));
        self.doc(
            "    ",
            &fmt::Sprintf!(
                "Leaves every optional argument to the engine; see [`%s`](Self::%s) to set them.",
                with_opts,
                with_opts
            ),
        );
        self.deprecation("    ", field);
        self.w(fmt::Sprintf!(
            concat!(
                "    pub fn %s(&self%s) -> %s {\n",
                "        self.%s(%s&%s::default())\n",
                "    }\n",
            ),
            name,
            params,
            return_type,
            with_opts,
            forward_list(&required),
            opts_type
        ));

        self.w("\n");
        self.doc("    ", &field_doc(field));
        self.deprecation("    ", field);
        self.w(fmt::Sprintf!(
            "    pub fn %s(&self%s, opts: &%s) -> %s {\n",
            with_opts,
            params,
            opts_param,
            return_type
        ));
        self.args_block(field, true);
        body(self);
        self.w("    }\n");
    }

    fn deprecation(&mut self, indent: &'static str, field: &Field) {
        if field.deprecated.Len() == 0 {
            return;
        }
        self.w(fmt::Sprintf!(
            "%s#[deprecated(note = %q)]\n",
            indent,
            field.deprecated
        ));
    }

    /// A field as a method on the object itself: it either extends the chain or
    /// sends a query.
    fn object_field(&mut self, ty: &Type, field: &Field) {
        let kind = field.ty.kind.clone();
        let is_object = kind == "OBJECT" || kind == "INTERFACE";

        if !is_object {
            let out = leaf_type(&field.ty);
            let selector = builder_call("Leaf", &out, field);
            self.field_pair(
                ty,
                field,
                string("Result<") + out + ", string>",
                &move |r| {
                    r.w(fmt::Sprintf!(
                        "        engine::fetch(&*self.transport, &self.q, &%s)\n",
                        selector
                    ));
                },
            );
            return;
        }

        if !field.ty.list {
            // A chain step. Nullability is the engine's to report when the
            // query runs; there is nothing to check here, and no round trip to
            // make one out of.
            let target = field.ty.name.clone();
            let graphql = field.name.clone();
            let args = args_expr(field);
            self.field_pair(ty, field, target.clone(), &move |r| {
                r.w(fmt::Sprintf!(
                    "        %s::new(self.transport.clone(), self.q.field(%q, %s))\n",
                    target,
                    graphql,
                    args
                ));
            });
            return;
        }

        // A list of objects. There is no chain that points at one element, so
        // the ids are fetched and each element rebuilt from its loader.
        let element = field.ty.name.clone();
        let loader = self.loader(&element);
        let id_type = self.id_type(&element);
        let (loader, id_type) = match (loader, id_type) {
            (Some(loader), Some(id_type)) => (loader, id_type),
            _ => {
                // A plain comment, not a doc comment: there is no item after it
                // to document, and a `///` with nothing under it would attach
                // itself to whatever method came next.
                self.w(fmt::Sprintf!(
                    concat!(
                        "\n",
                        "    // `%s` is a list of `%s`, which has no loader, so an element cannot be rebuilt on its own.\n",
                        "    // Read it through `fetch` instead, which needs no id.\n",
                    ),
                    rust_name(&field.name),
                    element
                ));
                return;
            }
        };

        let element = field.ty.name.clone();
        let builder = builder_call("ListField", &(element.clone() + "Fields"), field);
        self.field_pair(
            ty,
            field,
            string("Result<slice<") + element.clone() + ">, string>",
            &move |r| {
                r.w(fmt::Sprintf!(
                    "        let ids: slice<%s> = engine::fetch(\n",
                    id_type
                ));
                r.w("            &*self.transport,\n");
                r.w("            &self.q,\n");
                r.w(fmt::Sprintf!(
                    "            &%s.select(|f| f.id()),\n",
                    builder
                ));
                r.w("        )?;\n");
                r.w(fmt::Sprintf!(
                    "        let mut out = make!([]%s, 0, ids.Len());\n",
                    element
                ));
                r.w("        let mut i: int = 0;\n");
                r.w("        while i < ids.Len() {\n");
                r.w("            let mut __id = Args::new();\n");
                r.w("            __id.put(\"id\", arg_string(ids[i].clone()));\n");
                r.w("            out = append!(\n");
                r.w("                out,\n");
                r.w(fmt::Sprintf!(
                    "                %s::new(self.transport.clone(), Chain::root().field(%q, __id.finish()))\n",
                    element,
                    loader
                ));
                r.w("            );\n");
                r.w("            i += 1;\n");
                r.w("        }\n");
                r.w("        Ok(out)\n");
            },
        );
    }

    /// The same field as a node in a multi-field selection.
    fn selection_field(&mut self, ty: &Type, field: &Field) {
        let kind = field.ty.kind.clone();
        let is_object = kind == "OBJECT" || kind == "INTERFACE";

        // Which builder a field opens is decided by its shape: a scalar is a
        // leaf, and an object is one of three depending on whether it is
        // nullable or a list.
        let (kind, param) = if !is_object {
            ("Leaf", leaf_type(&field.ty))
        } else {
            let fields_type = field.ty.name.clone() + "Fields";
            if field.ty.list {
                ("ListField", fields_type)
            } else if field.ty.non_null {
                ("Field", fields_type)
            } else {
                ("OptField", fields_type)
            }
        };

        let return_type = fmt::Sprintf!("%s<%s>", kind, param);
        let builder = builder_call(kind, &param, field);
        self.field_pair(ty, field, return_type, &move |r| {
            r.w(fmt::Sprintf!("        %s\n", builder));
        });
    }

    // ─── schema lookups ───────────────────────────────────────────────

    /// The `loadXFromID` field on the root type, if the schema has one for
    /// `name`.
    fn loader(&self, name: &string) -> Option<string> {
        let query = self.schema.find(&self.schema.query_type)?;
        let loader = string("load") + name.clone() + "FromID";
        query.field(loader.clone()).map(|_| loader)
    }

    /// The Rust type `name`'s own `id` field decodes to.
    ///
    /// A nullable or list-typed `id` would not round-trip through a loader, so
    /// it counts as no id at all rather than as one to be unwrapped.
    fn id_type(&self, name: &string) -> Option<string> {
        let ty = self.schema.find(name)?;
        let id = ty.field("id")?;
        if !id.ty.non_null || id.ty.list {
            return None;
        }
        Some(leaf_type(&id.ty))
    }

    // ─── doc comments ─────────────────────────────────────────────────

    /// Write `text` as a `///` comment block, one line at a time.
    fn doc(&mut self, indent: &'static str, text: &string) {
        if text.Len() == 0 {
            return;
        }
        let lines = strings::Split(text.clone(), "\n");
        let mut i: int = 0;
        while i < lines.Len() {
            let line = strings::TrimRight(lines[i].clone(), "\r \t");
            if line.Len() == 0 {
                self.w(string(indent) + "///\n");
            } else {
                self.w(string(indent) + "/// " + line + "\n");
            }
            i += 1;
        }
    }
}

// ─── naming and typing, without the renderer ──────────────────────────

/// Introspection's own types, which a module never calls.
fn is_meta(name: &string) -> bool {
    strings::HasPrefix(name.clone(), "__")
}

/// The expression a body reads the field's rendered arguments from.
fn args_expr(field: &Field) -> string {
    if field.args.Len() == 0 {
        return string("string(\"\")");
    }
    string("__args.finish()")
}

fn method_name(field: &Field) -> string {
    let name = snake_case(&field.name);
    for reserved in RESERVED_METHODS {
        if name == *reserved {
            return escape_ident(name + "_field");
        }
    }
    escape_ident(name)
}

fn opts_method_name(field: &Field) -> string {
    let name = snake_case(&field.name);
    for reserved in RESERVED_METHODS {
        if name == *reserved {
            return escape_ident(name + "_field_opts");
        }
    }
    escape_ident(name + "_opts")
}

fn opts_name(ty: &Type, field: &Field) -> string {
    ty.name.clone() + upper_first(&field.name) + "Opts"
}

/// An argument is optional exactly when it is nullable.
fn optional_args(field: &Field) -> slice<InputValue> {
    let mut out = make!([]InputValue, 0, field.args.Len());
    let mut i: int = 0;
    while i < field.args.Len() {
        if !field.args[i].ty.non_null {
            out = append!(out, field.args[i].clone());
        }
        i += 1;
    }
    out
}

fn required_args(field: &Field) -> slice<InputValue> {
    let mut out = make!([]InputValue, 0, field.args.Len());
    let mut i: int = 0;
    while i < field.args.Len() {
        if field.args[i].ty.non_null {
            out = append!(out, field.args[i].clone());
        }
        i += 1;
    }
    out
}

/// `, path: impl Into<string>, args: &[&str]`
fn param_list(required: &slice<InputValue>) -> string {
    let mut out = string("");
    let mut i: int = 0;
    while i < required.Len() {
        out = out + ", " + rust_name(&required[i].name) + ": " + param_type(&required[i].ty);
        i += 1;
    }
    out
}

/// `path, args, ` — the same parameters passed straight through.
fn forward_list(required: &slice<InputValue>) -> string {
    let mut out = string("");
    let mut i: int = 0;
    while i < required.Len() {
        out = out + rust_name(&required[i].name) + ", ";
        i += 1;
    }
    out
}

/// Whether any optional argument borrows, and so puts a lifetime on the opts
/// struct. An opts struct of nothing but numbers, booleans and enums must not
/// declare one, or the parameter is unused and does not compile.
fn opts_borrows(optional: &slice<InputValue>) -> bool {
    let mut i: int = 0;
    while i < optional.Len() {
        let ty = &optional[i].ty;
        if ty.list || ty.kind == "INPUT_OBJECT" || (ty.kind == "SCALAR" && is_string_scalar(&ty.name))
        {
            return true;
        }
        i += 1;
    }
    false
}

/// Whether a scalar is carried as text. Everything but `Void` is.
fn is_string_scalar(name: &string) -> bool {
    name != "Int" && name != "Float" && name != "Boolean" && name != "Void"
}

/// The Rust type a scalar decodes to.
fn scalar_type(name: &string) -> string {
    if name == "Int" {
        return string("int");
    }
    if name == "Float" {
        return string("float64");
    }
    if name == "Boolean" {
        return string("bool");
    }
    if name == "Void" {
        return string("Void");
    }
    // `String`, `ID`, `Platform`, `JSON` and every `XxxID`: all text.
    string("string")
}

/// The Rust type one leaf of this schema type decodes to, wrappers included.
fn leaf_type(ty: &TypeRef) -> string {
    let base = if ty.kind == "SCALAR" {
        scalar_type(&ty.name)
    } else {
        ty.name.clone()
    };
    if ty.list {
        // Lists in this schema always hold non-null elements, in both field and
        // argument position, so there is no inner `Option` to render.
        let listed = string("slice<") + base + ">";
        if ty.non_null {
            return listed;
        }
        return string("Option<") + listed + ">";
    }
    if ty.non_null {
        return base;
    }
    string("Option<") + base + ">"
}

/// The type of one element of a list-typed argument.
fn element_param_type(ty: &TypeRef) -> string {
    if ty.kind == "ENUM" || ty.kind == "INPUT_OBJECT" {
        return ty.name.clone();
    }
    if is_string_scalar(&ty.name) {
        return string("&str");
    }
    scalar_type(&ty.name)
}

/// The type of a required argument in method position.
fn param_type(ty: &TypeRef) -> string {
    if ty.list {
        return string("&[") + element_param_type(ty) + "]";
    }
    if ty.kind == "ENUM" {
        return ty.name.clone();
    }
    if ty.kind == "INPUT_OBJECT" {
        return string("&") + ty.name.clone();
    }
    if is_string_scalar(&ty.name) {
        // Accepts a `&str` and a `string` alike, which is what makes
        // `from("alpine")` read the way it should.
        return string("impl Into<string>");
    }
    scalar_type(&ty.name)
}

/// The type of an optional argument as a field of an opts struct.
fn opts_field_type(ty: &TypeRef) -> string {
    if ty.list {
        // The elements are borrowed for the same `'a` as the slice: an elided
        // lifetime inside a struct field has nothing to be inferred from.
        let element = if ty.kind == "SCALAR" && is_string_scalar(&ty.name) {
            string("&'a str")
        } else {
            element_param_type(ty)
        };
        return string("Option<&'a [") + element + "]>";
    }
    if ty.kind == "ENUM" {
        return string("Option<") + ty.name.clone() + ">";
    }
    if ty.kind == "INPUT_OBJECT" {
        return string("Option<&'a ") + ty.name.clone() + ">";
    }
    if is_string_scalar(&ty.name) {
        return string("Option<&'a str>");
    }
    string("Option<") + scalar_type(&ty.name) + ">"
}

/// The type of an input object's own field, which is owned rather than
/// borrowed: a caller builds one and hands it over.
fn owned_field_type(ty: &TypeRef) -> string {
    let base = if ty.kind == "SCALAR" {
        scalar_type(&ty.name)
    } else {
        ty.name.clone()
    };
    let base = if ty.list {
        string("slice<") + base + ">"
    } else {
        base
    };
    if ty.non_null {
        return base;
    }
    string("Option<") + base + ">"
}

/// Whether [`encode`] wants a reference rather than a value: a list is passed
/// as a slice, and a string-shaped scalar as something that borrows into a
/// `string`. Everything else is small enough to encode through `&self`
/// autoref.
fn borrows_to_encode(ty: &TypeRef) -> bool {
    ty.list || (ty.kind == "SCALAR" && is_string_scalar(&ty.name))
}

/// How the value in `expr` becomes GraphQL argument text.
fn encode(expr: &string, ty: &TypeRef) -> string {
    if ty.list {
        return string("arg_list(") + expr.clone() + ")";
    }
    if ty.kind == "SCALAR" && is_string_scalar(&ty.name) {
        return string("arg_string(") + expr.clone() + ")";
    }
    expr.clone() + ".to_arg()"
}

/// The call that opens one of the four selection builders:
/// `Leaf::<string>::new("stdout")`, or
/// `ListField::<CrumbFields>::with_args("crumbs", __args.finish())`.
///
/// The `with_args` form is only reachable when the field has arguments, which
/// is also the only case where `args_block` emitted an `__args` to finish.
fn builder_call(kind: &'static str, param: &string, field: &Field) -> string {
    if field.args.Len() == 0 {
        return fmt::Sprintf!("%s::<%s>::new(%q)", kind, param, field.name);
    }
    fmt::Sprintf!(
        "%s::<%s>::with_args(%q, __args.finish())",
        kind,
        param,
        field.name
    )
}

/// A field's own documentation, with the engine's deprecation note appended.
fn field_doc(field: &Field) -> string {
    if field.deprecated.Len() == 0 {
        return field.doc.clone();
    }
    if field.doc.Len() == 0 {
        return string("Deprecated: ") + field.deprecated.clone();
    }
    field.doc.clone() + "\n\nDeprecated: " + field.deprecated.clone()
}

/// An argument's documentation, with its schema default noted.
fn arg_doc(arg: &InputValue) -> string {
    if arg.default_value.Len() == 0 {
        return arg.doc.clone();
    }
    if arg.doc.Len() == 0 {
        return string("Defaults to `") + arg.default_value.clone() + "`.";
    }
    arg.doc.clone() + "\n\nDefaults to `" + arg.default_value.clone() + "`."
}
